const fs = require('node:fs')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const mobile = path.resolve(__dirname, '..')
const root = path.resolve(mobile, '..')
const destination = path.join(mobile, 'nodejs-assets/nodejs-project')
fs.mkdirSync(destination, { recursive: true })
const licenses = path.join(destination, 'licenses/mobile')
fs.mkdirSync(licenses, { recursive: true })
fs.cpSync(path.join(mobile, 'third-party'), licenses, { recursive: true })
fs.copyFileSync(path.join(mobile, 'THIRD-PARTY-NOTICES.md'), path.join(licenses, 'NOTICES.md'))
for (const name of ['react', 'react-native', 'nodejs-mobile-react-native', 'react-native-webview', 'react-native-safe-area-context']) {
  const directory = path.join(mobile, 'node_modules', name)
  const license = fs.readdirSync(directory).find(file => /^LICENSE(?:\..*)?$/i.test(file))
  if (!license) throw new Error('Missing license for ' + name)
  fs.copyFileSync(path.join(directory, license), path.join(licenses, name + '.txt'))
}
const source = path.join(root, 'installer')
for (const name of ['installer.config.json', 'LICENSE', 'THIRD-PARTY-NOTICES.md']) fs.cpSync(path.join(source, name), path.join(destination, 'installer', name), { recursive: true })
fs.cpSync(path.join(source, 'src'), path.join(destination, 'installer/src'), { recursive: true, filter: file => !['main.cjs', 'preload.cjs', 'cloudflare-window.cjs', 'cloudflare-preload.cjs'].includes(path.basename(file)) })
fs.cpSync(path.join(root, 'updater/runtime'), path.join(destination, 'installer/src/runtime'), { recursive: true })
fs.copyFileSync(path.join(mobile, 'runtime/main.cjs'), path.join(destination, 'main.js'))
fs.copyFileSync(path.join(mobile, 'runtime/bridge.js'), path.join(destination, 'installer/src/renderer/mobile-bridge.js'))
const html = path.join(destination, 'installer/src/renderer/index.html')
let content = fs.readFileSync(html, 'utf8').replace('<script src="renderer.js">', '<script src="mobile-bridge.js"></script>\n  <script src="renderer.js">')
content = content.replaceAll('computer', 'phone').replace('Desktop setup code', 'Desktop setup code on TV')
content = content.replace('>Copy logs</button>', '>Share logs</button>').replace('id="save-logs"', 'id="save-logs" hidden').replace('id="open-logs"', 'id="open-logs" hidden')
fs.writeFileSync(html, content)
// Use the installer's locked production dependency graph, without Electron.
fs.copyFileSync(path.join(source, 'package.json'), path.join(destination, 'package.json'))
fs.copyFileSync(path.join(source, 'package-lock.json'), path.join(destination, 'package-lock.json'))
execFileSync(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['ci', '--omit=dev', '--ignore-scripts', '--no-audit'], { cwd: destination, stdio: 'inherit', windowsHide: true, shell: process.platform === 'win32' })
fs.writeFileSync(path.join(mobile, 'nodejs-assets/BUILD_NATIVE_MODULES.txt'), '0\n')
const pkg = JSON.parse(fs.readFileSync(path.join(source, 'package.json')))
fs.writeFileSync(path.join(destination, 'version.json'), JSON.stringify({ version: pkg.version }))
